# Generated by Django 3.1.7 on 2021-03-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20210318_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
